name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ hashFiles('VERSION') != '' }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Release
        run: |
          VERSION="$(cat VERSION)"
          gh release create v1.0.0+$VERSION \
            --title "v1.0.0 OpenAPI metadata ${VERSION}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
