name: Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'
      - 'METADATA'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Release
        if: ${{ hashFiles('VERSION') != '' }}
        run: |
          VERSION="$(cat VERSION)"
          METADATA="$(cat METADATA)"
          gh release create v$VERSION+$METADATA\
            --title "v${VERSION} OpenAPI metadata ${METADATA}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ secrets.PAT }}
